### PR TITLE
Move tau_m out of dot product

### PR DESCRIPTION
**Pull request by AlexVanMeegen**
Currently, the membrane time constant `tau_m` is multiplied with the input rate *before* calculating the dot product with the weights and indegrees. Since `tau_m` is a property of the postsynaptic neuron, this multiplication should be done *after* calculating the dot product imho ([Eq. 5 in Sanzeni et al. 2020](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008165#pcbi.1008165.e006)):
image

### CODE REVIEW

**Comment by moritzlayer** [comment]
That's true. The generalization from one `tau_m` to a vector of `tau_m` with one value for each population should hold after this change, would you agree?

**Comment by AlexVanMeegen** [comment]
Yes, the dot product should yield a vector with the input stats for each population.

**Comment by moritzlayer** [comment]
Perfect, I suppose we should fix the description of `tau_m` in the docstrings by writing "post-synaptic membrane time constant" instead of "membrane time constant". I recently adjusted the synaptic time constant docstrings to "pre-synaptic time constant" after our latest discussion.

**Comment by AlexVanMeegen** [comment]
Yes, good idea! I'll take care of that.

9 test currently fail, 8 of them belonging to the `Test_mean_input.test_correct_output` or `Test_std_input.test_correct_output` family and one `Test_external_rates_for_fixed_input.test_correct_output` with a rerr of `9.33097297e-06`. Do you know of they are all fixtures calculated with the previous code?

**Comment by moritzlayer** [comment]
I was expecting this. We have tests which test the fully vectorized case in which `tau_m` is defined as an array. Those should compare the new results with the old wrong results. So we need to run the fixture creation again, which I can do.

The `Test_external_rates_for_fixed_input.test_correct_output` could be a rounding thing due to the changed order of multiplications, looking at the relative error. But, it might as well be the fixture problem. Anyway, I don't think it's problematic.

**Comment by AlexVanMeegen** [comment]
I changed the docstrings. For completeness, here is the output of the failing `external_rates_for_fixed_input` test:
```
E       Max absolute difference: 7.310326e-05
E       Max relative difference: 9.33097297e-06
E        x: array([8.45684, 5.82741])
E        y: array([8.456767, 5.827355])
```

Anything left to do for me here?

**Comment by moritzlayer** [comment]
No, I will take care of the rest. Thanks a lot for fixing this!

**Comment by AlexVanMeegen** [comment]
Thanks for the final push!

**Pull request merged**
